# Generated by Django 3.2.1 on 2022-02-11 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('current_status', models.CharField(choices=[('WA', 'Awaiting assignment'), ('WL', 'Awaiting launch'), ('Rf', 'Refurbished'), ('T', 'Testing'), ('D', 'Destroyed'), ('L', 'Lost'), ('Rt', 'Retired')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('operator', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('launch_site', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Falcon9Launches.launchsite')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField(max_length=16)),
                ('date', models.DateField(verbose_name='date of flight')),
                ('outcome', models.CharField(choices=[('F', 'Failure'), ('S', 'Success'), ('C', 'Cancelled')], max_length=1)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Falcon9Launches.booster')),
                ('launch_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Falcon9Launches.launchsite')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Falcon9Launches.mission')),
            ],
        ),
    ]
