# Generated by Django 4.0.2 on 2022-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchcomplex',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(),
        ),
    ]
