# Generated by Django 4.0.2 on 2022-02-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0002_launchcomplex_image_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchcomplex',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
