# Generated by Django 4.0.2 on 2022-02-14 09:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0003_alter_launchcomplex_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
