# Generated by Django 4.0.2 on 2022-02-14 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0005_photo_remove_mission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchcomplex',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
