# Generated by Django 4.0.2 on 2022-02-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0008_launchcomplex_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_number',
            new_name='number',
        ),
    ]
