# Generated by Django 4.0.2 on 2022-02-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0009_rename_flight_number_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='launch_site',
        ),
        migrations.AddField(
            model_name='flight',
            name='launch_complex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Falcon9Launches.launchcomplex'),
            preserve_default=False,
        ),
    ]
