# Generated by Django 4.0.2 on 2022-02-16 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0011_alter_launchcomplex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchcomplex',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
