# Generated by Django 4.0.2 on 2022-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0012_alter_launchcomplex_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='wikiLink',
            field=models.URLField(null=True),
        ),
    ]
