# Generated by Django 4.0.2 on 2022-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Falcon9Launches', '0013_mission_wikilink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
